import type { Movement, Product } from "./types";

const t0 = "2026-08-18T09:00:00.000Z";
const t1 = "2026-08-22T14:20:00.000Z";
const t2 = "2026-08-28T11:05:00.000Z";
const t3 = "2026-09-01T16:40:00.000Z";
const t4 = "2026-09-02T08:15:00.000Z";

export const SEED_PRODUCTS: Product[] = [
  {
    id: "prd_saw_014",
    sku: "SM-SAW-014",
    name: "Japanese Ryoba Saw 240mm",
    category: "Cutting",
    location: "Bay A · Bin 04",
    quantity: 6,
    minQuantity: 3,
    unit: "ea",
    unitCost: 72,
    notes: "Rip and crosscut teeth. Keep the spine oiled.",
    createdAt: t0,
    updatedAt: t3,
  },
  {
    id: "prd_pln_004",
    sku: "SM-PLN-004",
    name: "No. 4 Smoothing Plane",
    category: "Cutting",
    location: "Bay A · Bin 01",
    quantity: 2,
    minQuantity: 2,
    unit: "ea",
    unitCost: 189,
    notes: "A2 iron, 25° primary bevel. One on the bench, one in reserve.",
    createdAt: t0,
    updatedAt: t4,
    lastIdentifiedAt: t4,
  },
  {
    id: "prd_chl_018",
    sku: "SM-CHL-018",
    name: "Cabinetmaker’s Chisel 18mm",
    category: "Cutting",
    location: "Bay A · Bin 07",
    quantity: 9,
    minQuantity: 4,
    unit: "ea",
    unitCost: 34,
    notes: "Bevel-edge, hornbeam handle.",
    createdAt: t0,
    updatedAt: t1,
  },
  {
    id: "prd_oil_500",
    sku: "SM-OIL-500",
    name: "Cold-pressed Linseed Oil 500ml",
    category: "Finish",
    location: "Bay C · Shelf 2",
    quantity: 4,
    minQuantity: 6,
    unit: "btl",
    unitCost: 18,
    notes: "Rags go in the quench bucket — spontaneous combustion risk.",
    createdAt: t0,
    updatedAt: t2,
  },
  {
    id: "prd_wax_120",
    sku: "SM-WAX-120",
    name: "Beeswax Furniture Paste 120g",
    category: "Finish",
    location: "Bay C · Shelf 2",
    quantity: 11,
    minQuantity: 4,
    unit: "tin",
    unitCost: 14,
    notes: "Buff with a clean cotton cloth.",
    createdAt: t0,
    updatedAt: t1,
  },
  {
    id: "prd_shl_090",
    sku: "SM-SHL-090",
    name: "Blonde Shellac Flakes 90g",
    category: "Finish",
    location: "Bay C · Shelf 3",
    quantity: 0,
    minQuantity: 2,
    unit: "bag",
    unitCost: 16,
    notes: "Cut a 2 lb in denatured alcohol. Last bag used on the ash cabinet.",
    createdAt: t0,
    updatedAt: t3,
  },
  {
    id: "prd_knb_008",
    sku: "SM-KNB-008",
    name: "Aged Brass Cabinet Knobs",
    category: "Hardware",
    location: "Bay B · Drawer 3",
    quantity: 48,
    minQuantity: 16,
    unit: "ea",
    unitCost: 6.5,
    notes: "Sold in eights. Unlacquered — will patina.",
    createdAt: t0,
    updatedAt: t2,
  },
  {
    id: "prd_hng_075",
    sku: "SM-HNG-075",
    name: "Butt Hinges 75mm (pair)",
    category: "Hardware",
    location: "Bay B · Drawer 1",
    quantity: 14,
    minQuantity: 8,
    unit: "pr",
    unitCost: 11,
    notes: "Solid brass, includes screws.",
    createdAt: t0,
    updatedAt: t1,
  },
  {
    id: "prd_vsh_012",
    sku: "SM-VSH-012",
    name: "Steel Shelf Pins 5mm",
    category: "Hardware",
    location: "Bay B · Drawer 4",
    quantity: 120,
    minQuantity: 40,
    unit: "ea",
    unitCost: 0.35,
    notes: "Nickel plated. 5mm for 32mm system.",
    createdAt: t0,
    updatedAt: t0,
  },
  {
    id: "prd_ppr_080",
    sku: "SM-PPR-080",
    name: "Garnet Sandpaper 80 Grit",
    category: "Abrasives",
    location: "Bay C · Rack 1",
    quantity: 18,
    minQuantity: 20,
    unit: "sht",
    unitCost: 1.2,
    notes: "Sheets, 230 × 280mm. Reorder from the mill.",
    createdAt: t0,
    updatedAt: t4,
  },
  {
    id: "prd_ppr_220",
    sku: "SM-PPR-220",
    name: "Garnet Sandpaper 220 Grit",
    category: "Abrasives",
    location: "Bay C · Rack 1",
    quantity: 42,
    minQuantity: 20,
    unit: "sht",
    unitCost: 1.2,
    notes: "Finish sanding before oil.",
    createdAt: t0,
    updatedAt: t1,
  },
  {
    id: "prd_blk_002",
    sku: "SM-BLK-002",
    name: "Cast Iron Bench Dogs",
    category: "Workholding",
    location: "Bay A · Bin 12",
    quantity: 8,
    minQuantity: 4,
    unit: "ea",
    unitCost: 22,
    notes: "19mm round. Fit the French oak bench.",
    createdAt: t0,
    updatedAt: t0,
  },
  {
    id: "prd_clp_024",
    sku: "SM-CLP-024",
    name: "F-Clamp 24 inch",
    category: "Workholding",
    location: "Bay A · Rail",
    quantity: 3,
    minQuantity: 6,
    unit: "ea",
    unitCost: 28,
    notes: "Two out on the glue-up table.",
    createdAt: t0,
    updatedAt: t3,
  },
  {
    id: "prd_glh_250",
    sku: "SM-GLH-250",
    name: "Hide Glue Pearls 250g",
    category: "Consumables",
    location: "Bay C · Shelf 4",
    quantity: 5,
    minQuantity: 2,
    unit: "bag",
    unitCost: 19,
    notes: "192g bloom. Warm to 60°C, never boil.",
    createdAt: t0,
    updatedAt: t2,
  },
  {
    id: "prd_msk_024",
    sku: "SM-MSK-024",
    name: "Paper Masking Tape 24mm",
    category: "Consumables",
    location: "Bay C · Peg 8",
    quantity: 7,
    minQuantity: 4,
    unit: "rl",
    unitCost: 4.5,
    notes: "Low-tack for finish work.",
    createdAt: t0,
    updatedAt: t1,
  },
  {
    id: "prd_dwl_064",
    sku: "SM-DWL-064",
    name: "Walnut Dowels 8mm",
    category: "Consumables",
    location: "Bay B · Bin 09",
    quantity: 64,
    minQuantity: 24,
    unit: "ea",
    unitCost: 0.55,
    notes: "Fluted, 40mm length. Match the walnut sideboard run.",
    createdAt: t0,
    updatedAt: t2,
  },
];

export const SEED_MOVEMENTS: Movement[] = [
  {
    id: "mov_001",
    productId: "prd_pln_004",
    sku: "SM-PLN-004",
    productName: "No. 4 Smoothing Plane",
    type: "pick",
    delta: -1,
    quantityAfter: 2,
    note: "Issued to bench 2",
    at: t4,
  },
  {
    id: "mov_002",
    productId: "prd_ppr_080",
    sku: "SM-PPR-080",
    productName: "Garnet Sandpaper 80 Grit",
    type: "pick",
    delta: -8,
    quantityAfter: 18,
    note: "Oak carcass mill",
    at: t4,
  },
  {
    id: "mov_003",
    productId: "prd_shl_090",
    sku: "SM-SHL-090",
    productName: "Blonde Shellac Flakes 90g",
    type: "pick",
    delta: -2,
    quantityAfter: 0,
    note: "Ash cabinet, last bags",
    at: t3,
  },
  {
    id: "mov_004",
    productId: "prd_clp_024",
    sku: "SM-CLP-024",
    productName: "F-Clamp 24 inch",
    type: "pick",
    delta: -2,
    quantityAfter: 3,
    at: t3,
  },
  {
    id: "mov_005",
    productId: "prd_saw_014",
    sku: "SM-SAW-014",
    productName: "Japanese Ryoba Saw 240mm",
    type: "receive",
    delta: 4,
    quantityAfter: 6,
    note: "Tools Japan restock",
    at: t3,
  },
  {
    id: "mov_006",
    productId: "prd_oil_500",
    sku: "SM-OIL-500",
    productName: "Cold-pressed Linseed Oil 500ml",
    type: "pick",
    delta: -3,
    quantityAfter: 4,
    at: t2,
  },
  {
    id: "mov_007",
    productId: "prd_knb_008",
    sku: "SM-KNB-008",
    productName: "Aged Brass Cabinet Knobs",
    type: "receive",
    delta: 24,
    quantityAfter: 48,
    note: "Hardware house",
    at: t2,
  },
  {
    id: "mov_008",
    productId: "prd_glh_250",
    sku: "SM-GLH-250",
    productName: "Hide Glue Pearls 250g",
    type: "receive",
    delta: 3,
    quantityAfter: 5,
    at: t2,
  },
];

export function cloneSeedProducts(): Product[] {
  return SEED_PRODUCTS.map((p) => ({ ...p }));
}

export function cloneSeedMovements(): Movement[] {
  return SEED_MOVEMENTS.map((m) => ({ ...m }));
}
