/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppActivityRouteImport } from './routes/_app/activity'
import { Route as AppCatalogRouteImport } from './routes/_app/catalog'
import { Route as AppScanRouteImport } from './routes/_app/scan'
import { Route as AppCatalogIdRouteImport } from './routes/_app/catalog.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogRoute = AppCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AppRoute,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogIdRoute = AppCatalogIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCatalogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/activity': typeof AppActivityRoute
  '/catalog': typeof AppCatalogRouteWithChildren
  '/scan': typeof AppScanRoute
  '/catalog/$id': typeof AppCatalogIdRoute
}
export interface FileRoutesByTo {
  '/activity': typeof AppActivityRoute
  '/catalog': typeof AppCatalogRouteWithChildren
  '/scan': typeof AppScanRoute
  '/': typeof AppIndexRoute
  '/catalog/$id': typeof AppCatalogIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/activity': typeof AppActivityRoute
  '/_app/catalog': typeof AppCatalogRouteWithChildren
  '/_app/scan': typeof AppScanRoute
  '/_app/': typeof AppIndexRoute
  '/_app/catalog/$id': typeof AppCatalogIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/activity' | '/catalog' | '/scan' | '/catalog/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/activity' | '/catalog' | '/scan' | '/' | '/catalog/$id'
  id:
    | '__root__'
    | '/_app'
    | '/_app/activity'
    | '/_app/catalog'
    | '/_app/scan'
    | '/_app/'
    | '/_app/catalog/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog': {
      id: '/_app/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AppCatalogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scan': {
      id: '/_app/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog/$id': {
      id: '/_app/catalog/$id'
      path: '/$id'
      fullPath: '/catalog/$id'
      preLoaderRoute: typeof AppCatalogIdRouteImport
      parentRoute: typeof AppCatalogRoute
    }
  }
}

interface AppCatalogRouteChildren {
  AppCatalogIdRoute: typeof AppCatalogIdRoute
}

const AppCatalogRouteChildren: AppCatalogRouteChildren = {
  AppCatalogIdRoute: AppCatalogIdRoute,
}

const AppCatalogRouteWithChildren = AppCatalogRoute._addFileChildren(
  AppCatalogRouteChildren,
)

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppCatalogRoute: typeof AppCatalogRouteWithChildren
  AppScanRoute: typeof AppScanRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppCatalogRoute: AppCatalogRouteWithChildren,
  AppScanRoute: AppScanRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
